[project]
name = "tokenization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.1",
    "tokenizers>=0.22.1",
    "torch>=2.9.1",
    "transformers>=4.57.1",
    "zstandard>=0.25.0",
]
